logging:
    pattern:
        console: "[Kafka Order] %clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
server:
    port: 9001
spring:
    application:
        name: kafka-order
    main:
        banner-mode: off
        log-startup-info: false
    h2:
        console:
            enabled: true
    datasource:
        url: jdbc:h2:mem:kafkaorderdb
    kafka:
        listener:
            missing-topics-fatal: false
        producer:
            bootstrap-servers:
                - localhost:9092
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
            compression-type: snappy
            batch-size: 32768            
        consumer:
            group-id: kafka-order-cg
            enable-auto-commit: true
            auto-offset-reset: earliest
            bootstrap-servers:
                - localhost:9092
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer        
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            properties:
                spring:
                    json:
                        trusted:
                            packages: com.imagina.kafka.broker.message
                        value:
                            default:
                                type: java.lang.Object
        properties:
            request:
                timeout:
                    ms: 10000
            delivery:
                timeout:
                    ms: 30000
            enable:
                idempotence: true
            linger:
                ms: 15000