logging:
  pattern:
    console: "[Kafka Core Consumer] %clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} [%t] %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"

spring:
  application:
    name: core-consumer
  kafka:
    consumer:
      group-id: kafka-core-consumer-group
      auto-offset-reset: earliest
      max-poll-records: 4
    listener:
      ack-mode: batch